Add maven example for schema compatibility check (#12)

diff --git a/.github/workflows/kafka-app.yml b/.github/workflows/kafka-app.yml
--- a/.github/workflows/kafka-app.yml
+++ b/.github/workflows/kafka-app.yml
@@ -1,4 +1,4 @@
-name: python-kafka-app
+name: kafka-app
 
 on: [push]
 
@@ -6,12 +6,12 @@ env:
   # General
   DEST_WORKSPACE: ${{ github.workspace }}
   NETWORK: workspace_default
-  TOPIC: t20
+  TOPIC: t3
   CONFLUENT_BOOTSTRAP_SERVERS: ${{ secrets.CONFLUENT_BOOTSTRAP_SERVERS }}
   CONFLUENT_API_KEY: ${{ secrets.CONFLUENT_API_KEY }}
   CONFLUENT_API_SECRET: ${{ secrets.CONFLUENT_API_SECRET }}
   # Confluent Cloud Schema Registry and AVRO
-  TOPICAVRO: t21-avro
+  TOPICAVRO: t3-avro
   CONFLUENT_SCHEMA_REGISTRY_URL: ${{ secrets.CONFLUENT_SCHEMA_REGISTRY_URL }}
   CONFLUENT_BASIC_AUTH_USER_INFO: ${{ secrets.CONFLUENT_BASIC_AUTH_USER_INFO }}
 
@@ -40,7 +40,7 @@ jobs:
         with:
           context: .
           push: true
-          tags: ghcr.io/${{ github.actor }}/python-app:latest
+          tags: ghcr.io/${{ github.actor }}/kafka-app:latest
 
   unit:
 
@@ -56,7 +56,7 @@ jobs:
         run: |
           docker run -t -e TOPIC=$TOPIC \
                        -v ${DEST_WORKSPACE}/configs/librdkafka.unit.config:/etc/librdkafka.config \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c '/usr/bin/producer.py -f /etc/librdkafka.config -t $TOPIC'
 
   local:
@@ -79,12 +79,12 @@ jobs:
           docker run -t -e TOPIC=$TOPIC \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.local.config:/etc/librdkafka.config \
                         --net ${NETWORK} \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c '/usr/bin/producer.py -f /etc/librdkafka.config -t $TOPIC'
           docker run -t -e TOPIC=$TOPIC \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.local.config:/etc/librdkafka.config \
                         --net ${NETWORK} \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c 'timeout 10s /usr/bin/consumer.py -f /etc/librdkafka.config -t $TOPIC' \
                           || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
 
@@ -111,12 +111,12 @@ jobs:
           docker run -t -e TOPICAVRO=$TOPICAVRO \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.local-avro.config:/etc/librdkafka.config \
                         --net ${NETWORK} \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c '/usr/bin/producer_ccsr.py -f /etc/librdkafka.config -t $TOPICAVRO'
           docker run -t -e TOPICAVRO=$TOPICAVRO \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.local-avro.config:/etc/librdkafka.config \
                         --net ${NETWORK} \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c 'timeout 10s /usr/bin/consumer_ccsr.py -f /etc/librdkafka.config -t $TOPICAVRO' \
                           || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
 
@@ -143,11 +143,11 @@ jobs:
         run: |
           docker run -t -e TOPIC=$TOPIC \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.ccloud.config:/etc/librdkafka.config \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c '/usr/bin/producer.py -f /etc/librdkafka.config -t $TOPIC'
           docker run -t -e TOPIC=$TOPIC \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.ccloud.config:/etc/librdkafka.config \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c 'timeout 10s /usr/bin/consumer.py -f /etc/librdkafka.config -t $TOPIC' \
                           || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
 
@@ -174,18 +174,18 @@ jobs:
         run: |
           docker run -t -e TOPICAVRO=$TOPICAVRO \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.ccloud-avro.config:/etc/librdkafka.config \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c '/usr/bin/producer_ccsr.py -f /etc/librdkafka.config -t $TOPICAVRO'
           docker run -t -e TOPICAVRO=$TOPICAVRO \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.ccloud-avro.config:/etc/librdkafka.config \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c 'timeout 10s /usr/bin/consumer_ccsr.py -f /etc/librdkafka.config -t $TOPICAVRO' \
                           || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
 
       - name: Test message count
         run: tests/ccloud-avro.sh $TOPICAVRO
 
-  ccloud-schema-compatibility:
+  ccloud-python-schema-compatibility:
 
     needs: ccloud-avro
 
@@ -203,12 +203,43 @@ jobs:
 
       - name: Test compatibility of a new schema
         run: |
+          # Pass
           docker run -t -e TOPICAVRO=$TOPICAVRO \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.ccloud-avro.config:/etc/librdkafka.config \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c '/usr/bin/test_schema_compatibility.py -f /etc/librdkafka.config -t $TOPICAVRO -s /etc/Count-pass.avsc'
-          # The -e flag sets expected_pass to False
+          # Fail; the -e flag sets expected_pass to False
           docker run -t -e TOPICAVRO=$TOPICAVRO \
                         -v ${DEST_WORKSPACE}/configs/librdkafka.ccloud-avro.config:/etc/librdkafka.config \
-                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
+                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                         bash -c '/usr/bin/test_schema_compatibility.py -f /etc/librdkafka.config -t $TOPICAVRO -s /etc/Count-fail.avsc -e'
+
+  ccloud-java-schema-compatibility:
+
+    needs: ccloud-avro
+
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - uses: actions/checkout@v2
+
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          cache: maven
+
+      - name: Test compatibility of a new schema
+        run: |
+          # Pass
+          mvn io.confluent:kafka-schema-registry-maven-plugin:test-compatibility \
+              "-DschemaRegistryUrl=$CONFLUENT_SCHEMA_REGISTRY_URL" \
+              "-DschemaRegistryBasicAuthUserInfo=$CONFLUENT_BASIC_AUTH_USER_INFO" \
+              "-DnewSchema=schemas/Count-pass.avsc"
+          # Fail
+          mvn io.confluent:kafka-schema-registry-maven-plugin:test-compatibility \
+              "-DschemaRegistryUrl=$CONFLUENT_SCHEMA_REGISTRY_URL" \
+              "-DschemaRegistryBasicAuthUserInfo=$CONFLUENT_BASIC_AUTH_USER_INFO" \
+              "-DnewSchema=schemas/Count-fail.avsc" || echo "Ok: Expected to fail"
