Test mvn example GitHub workflow

diff --git a/.github/workflows/python-kafka-app.yml b/.github/workflows/python-kafka-app.yml
--- a/.github/workflows/python-kafka-app.yml
+++ b/.github/workflows/python-kafka-app.yml
@@ -185,7 +185,7 @@ jobs:
       - name: Test message count
         run: tests/ccloud-avro.sh $TOPICAVRO
 
-  ccloud-schema-compatibility:
+  ccloud-schema-compatibility-python:
 
     needs: ccloud-avro
 
@@ -212,3 +212,29 @@ jobs:
                         -v ${DEST_WORKSPACE}/configs/librdkafka.ccloud-avro.config:/etc/librdkafka.config \
                         --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
                         bash -c '/usr/bin/test_schema_compatibility.py -f /etc/librdkafka.config -t $TOPICAVRO -s /etc/Count-fail.avsc -e'
+
+  ccloud-schema-compatibility-java:
+
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - uses: actions/checkout@v2
+
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          cache: maven
+
+      - name: Test compatibility of a new schema
+        run: |
+          mvn io.confluent:kafka-schema-registry-maven-plugin:test-compatibility \
+              "-DschemaRegistryUrl=$CONFLUENT_SCHEMA_REGISTRY_URL" \
+              "-DschemaRegistryBasicAuthUserInfo=$CONFLUENT_BASIC_AUTH_USER_INFO" \
+              "-DnewSchema=schemas/Count-pass.avsc"
+          mvn io.confluent:kafka-schema-registry-maven-plugin:test-compatibility \
+              "-DschemaRegistryUrl=$CONFLUENT_SCHEMA_REGISTRY_URL" \
+              "-DschemaRegistryBasicAuthUserInfo=$CONFLUENT_BASIC_AUTH_USER_INFO" \
+              "-DnewSchema=schemas/Count-fail.avsc" || echo "Ok: Expected to fail"
